export const words = [
    {word: "cheese", def: "something tasty", category: "random" },
    {word: "news", def: "recent events and information.", category: "random" },
    {word: "requirement", def: "a thing that is needed or wanted.", category: "random" },
    {word: "formal", def: "done in accordance with convention or etiquette; suitable for or constituting an official or important occasion.", category: "random" },
    {word: "manage", def: "be in charge of.", category: "random" },
    {word: "depart", def: "leave, especially in order to start a journey.", category: "random" },
    {word: "definite", def: "clearly stated or decided; not vague or doubtful.", category: "random" },
    {word: "ridge", def: "a long, narrow hilltop, mountain range, or watershed.", category: "random" },
    {word: "content", def: "in a state of peaceful happiness.", category: "random" },
    {word: "fragment", def: "occurring or done many times at short intervals.", category: "random" },
    {word: "integrity", def: "the quality of being honest and having strong moral principles.", category: "random" },
    {word: "humans", def: "what you are.", category: "random" },
    {word: "jazz", def: "A music style.", category: "random" },
    {word: "hangman", def: "A game.", category: "random" },
    {word: "confuse", def: "make (someone) bewildered or perplexed.", category: "random" },
    {word: "sunrise", def: "a time in the morning.", category: "random" },

    {word: "Star Wars", def: "an old movie", category: "movie" },
    {word: "lord of the rings", def: "a movie about a ring", category: "movie" },
    {word: "Lord of the flies", def: "a kids movie", category: "movie" },
    {word: "Lord of the dance", def: "an Irish movie", category: "movie" },
    {word: "jurassic park", def: "A dinosaur movie", category: "movie" },
    {word: "mission imposible", def: "spys", category: "movie" },
    {word: "groundhog day", def: "time loop", category: "movie" },
    {word: "shrek", def: "green onion", category: "movie" },
    {word: "harry potter", def: "wizards", category: "movie" },
    {word: "how to train your dragon", def: "dragons", category: "movie" },
    {word: "inception", def: "dreams", category: "movie" },
    {word: "the matrix", def: "simulation", category: "movie" },
    {word: "john wick", def: "gun-fu", category: "movie" },
    {word: "back to the future", def: "time travel", category: "movie" },
    {word: "cast away", def: "Lost on an island", category: "movie" },
    {word: "labyrinth", def: "a maze", category: "movie" },
    {word: "shaun of the dead", def: "zombies cornetto", category: "movie" },
    {word: "hot fuzz", def: "police cornetto", category: "movie" },
    {word: "worlds end", def: "pubs cornetto", category: "movie" },
    {word: "bee movie", def: "bees with humans", category: "movie" },

    {word: "the A team", def: "a team", category: "tvshow" },
    {word: "the IT crowd", def: "an IT team", category: "tvshow"},
    {word: "stranger things", def: "upside down", category: "tvshow"},
    {word: "friends", def: "people who will be there for you when the rain starts to fall", category: "tvshow"},
    {word: "the mandalorian", def: "space bounty hunter", category: "tvshow"},
    {word: "community", def: "6 seasons and a movie", category: "tvshow"},
    {word: "dirk gentlys holistic detective agency", def: "everthing is connected", category: "tvshow"},
    {word: "queens gambit", def: "chess", category: "tvshow"},
    {word: "star trek", def: "picard or kirk", category: "tvshow"},
    {word: "the office", def: "the best boss", category: "tvshow"},
    {word: "brooklyn nine nine", def: "NINE! NINE!", category: "tvshow"},

];